blank_issues_enabled: false
contact_links:
  - name: boringproxy forum
    url: https://forum.indiebits.io/c/boringproxy/9
    about:
      Please ask questions and submit bug reports on the IndieBits boringproxy forum
